### ISSUE TITLE
“Probability is a number between 0 and 127”

### ISSUE THREAD

**Issue by Wuzzy2** [octacian/advschem#1] opened 2017-08-12 13:49 UTC
“Probability is a number between 0 and 127”.

This is false, it must be between 0 and 255.

**Comment by octacian** [comment] 2017-08-13 15:10
Nope, that's purposeful, it is supposed to be between 0 and 127. The schematic documentation is really horrible. Probability is split into two categories.

Numbers from 0-127 change the probability of a node being placed, only if the placement of that node would not overwrite another non-air node (i.e. the node is *not* force-placed). Probability between 128 and 255 causes a forced placement of the node but still maintains a probability as to whether or not the node is placed at all (i.e. the node *is* force-placed).

**Comment by Wuzzy2** [comment] 2017-08-13 20:05
OMG.

**Comment by octacian** [comment] 2017-08-13 20:23
Sounds about like how everyone else reacted when paramat finally explained it in #minetest-hub - after inspecting the code for 30+ minutes. :joy: Anyways, I think the API documentation was updated to include this information, I saw a PR regarding something of this sort go through a while ago.

**Comment by paramat** [comment] 2017-08-13 21:51
Not sure about this, best read through our discussion in IRC.
MTGame tree schematics are working correctly as implied by the docs.

**Comment by paramat** [comment] 2017-08-13 21:56
http://irc.minetest.net/minetest-hub/2017-07-24#i_5019707 onwards.
http://irc.minetest.net/minetest-hub/2017-07-24#i_5019823 docs may be right.
The confusion may come from the difference between how prob is entered in a lua table schematic (as per docs) and how the values are encoded elsewhere (in the probability list).
MTGame tree schematics act as if the docs are correct for how to use the values in a lua table schematic.

**Comment by paramat** [comment] 2017-08-13 22:06
octacian what you're describing is how the probability list has to be encoded, as we discovered in our discussion, that is different to how prob values are manually entered into a lua table schematic.

**Comment by Wuzzy2** [comment] 2017-08-13 22:10
So … to summarize:
This issue is valid.

**Comment by paramat** [comment] 2017-08-13 22:25
Not necessarily, where did you see “Probability is a number between 0 and 127”? That is correct for a probability list because that uses the normally hidden encoding not used when manually entering values in a lua tabel schematic.

**Comment by paramat** [comment] 2017-08-13 22:31
Ok i see the wording in the formspec.
This mod is asking for probability to be entered in the raw encoded form instead of the lua table form, so it is functionally correct, but to avoid confusion it shoukd be consistent with lua table values and ask for 0-255 then divide by 2, then add 128 for per-node force place. I think i have said this before.
So the issue is valid, and docs are correct.

**Comment by paramat** [comment] 2017-08-13 22:35
Yes http://irc.minetest.net/minetest-hub/2017-07-25#i_5020014
"but better for consistency that you ask the mod user to enter 0-255, then divide that by 2 to get 0-127"
That should be done to avoid much confusion.

**Comment by octacian** [comment] 2017-08-14 01:01
hmm. I will modify as paramat suggested as soon as I get a chance. I didn't realize it was still different in the Lua table form, thanks for clearing that up. So yeah, although this is technically functional from 0-127, it isn't very consistent; but I'll do something.

Sorry, my misunderstanding probably made this issue a bit more confusing.

**Comment by octacian** [comment] 2018-03-13 19:58
Closing. See https://forum.minetest.net/viewtopic.php?f=11&t=18515&p=314273#p314273 (Wuzzy's version).

**Closed as completed by octacian** 2018-03-13 19:58 UTC
